### ISSUE TITLE
Custom weight functions

### ISSUE THREAD

**Issue by mgei** [rubetron/AssetAllocation#1]
Nice package.

I was wondering how `ivy_port_weights()` can be used.

From what I see, `backtest_allocation()` only supports constant weights (portfolio_rule_fn = "identity").

Do you plan on extending this?

Thanks.

**Comment by rubetron** [comment]
Thanks. I'm going to push an update soon with support for tactical allocations. There will be a function for the Ivy Portfolio which will replace the ivy_port_weights() function.

**Comment by rubetron** [comment]
This has been done in the last update.
